source 'http://rubygems.org'
gem 'redis'
gem 'rails'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'haml'
gem 'high_voltage'
gem 'dropbox'
gem 'compass'
gem 'formtastic'
gem 'heroku'
gem 'redcarpet'
gem 'liquid'
gem 'liquid-inheritance'
gem 'dalli'
gem 'redis'
gem 'redis-objects'
group :test, :development do
	gem 'rspec'
	gem 'rspec-rails'
	gem 'cucumber-rails'
	gem 'factory_girl_rails'
	gem 'autotest'
	gem 'nokogiri'
	gem 'capybara'
	gem 'database_cleaner'
	gem 'capybara'
	gem 'launchy'
end

