source 'http://rubygems.org'
gem 'rails'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'haml'
gem 'high_voltage'
gem 'dropbox'
gem 'compass'
gem 'formtastic'
gem 'heroku'
gem 'redcarpet'
gem 'RedCloth', ">= 4.2.7"
gem 'rdiscount'
gem 'liquid'
gem 'liquid-inheritance'
gem 'dalli'
gem 'redis'
gem 'redis-objects'
gem "aws-ses", "~> 0.3.2", :require => 'aws/ses'
gem "aws-s3"
gem 'fakeweb'
gem 'omniauth', ">= 0.2.0"#,:path => "vendor/omniauth"
gem 'gstore'
group :test, :development do
	gem 'rspec'
	gem 'rspec-rails'
	gem 'cucumber-rails'
	gem 'factory_girl_rails'
	gem 'autotest'
	gem 'nokogiri'
	gem 'capybara'
	gem 'capybara-webkit'
	gem 'database_cleaner'
	gem 'launchy'
  gem 'spork','0.9.0.rc8'
  gem 'rb-fsevent'
  gem 'guard-spork'
  gem 'shoulda-matchers'
end

